version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: nestjs_main
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: 123123123
    ports:
      - "5430:5432"
